### ISSUE TITLE
Question Time: Are values linked and how to update them later?

### ISSUE THREAD

**Issue by cookiengineer** [wilddamon/typedom-demos#1]
First: I'm looking forward to see typed-om in future. This will have huge impact on how people translate OpenGL-based codebases (or engines) to the web without having to wrap elements in WebGL contexts.

I have a question regarding the code samples in your demos:

``` javascript
var translation = new CSSTranslation(
    new CSSSimpleLength(position[0], 'px'),
    new CSSSimpleLength(position[1], 'px')
);

var position = new TransformValue([ translation ]);

some_element.styleMap.set('transform', position);
```

Does this mean that the instance of CSSTranslation is linked behind the scenes as it's an Object instance?

The spec kind of implies that you can reuse references to the lengths (like `var x = new CSSSimpleLength(13,'px'); x.attribute = 37;` or via `translation.x.attribute = 37`) but I'm unsure if that is already supported.

That would heavily improve the render cycles and heavily reduce unnecessary garbage in the v8 context.

**Comment by wilddamon** [comment]
Hi Cookie,

Instances of CSSStyleValue and its subclasses are not "live" - they're just JS objects holding values, so modifying them has no effect on styles until you call set on the styleMap. From what I understand, there would be a pretty significant memory and complexity overhead if we made the objects link in behind the scenes as you say.

This means that `var x = styleMap.get('width'); x.value = 500`, doesn't do anything useful, since you're not modifying a live object.

For more details, the spec for Typed OM can be viewed here: https://drafts.css-houdini.org/css-typed-om/, issues/questions about the spec can be filed here: https://github.com/w3c/css-houdini-drafts
